### ISSUE TITLE
[Site] 400 errors on GET items JPEG

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#10]
**Steps to reproduce:**
1. Open site;
2. Navigate to prom-and-party-dresses/vessna-2019 page;
3. Click on any item preview image.

**Expected result:** Item info pop-up appears. Image and info of selected item is displaying;
**Actual result:** Item info pop-up appears. No image or data is displaying. 400 errors appear in Console.
![Screenshot_5](https://user-images.githubusercontent.com/37796643/58132316-a37ea480-7c29-11e9-9696-7173c849b54e.jpg)

**Comment by followyouhome** [comment]
Ugg, something weird, can't reproduce, but won't close it now

**Comment by ypogarsky** [comment]
Passed.
