### ISSUE TITLE
[Site] User is able to use 'Подписаться' function with empty 'E-mail' field 

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#13]
**Steps to reproduce:**
1. Open browser (Microsoft Edge, Chrome);
2. Open site;
3. Scroll down till the footer;
4. Click on [Подписаться] button;
5. Do not populate any fields. Check 'Даю согласие на обработку персональных данных' check-box and click on [Отправить] button.

**Expected result:** Request is not submited. Validation message appears: "Пожалуйста укажите Ваш электронный адрес"
**Actual result:** Request is submited. Validation message appears: "Подписка оформленна"

**Comment by followyouhome** [comment]
Added default html5 validation on UI side + added validation on server side

**Comment by ypogarsky** [comment]
Passed.
