### ISSUE TITLE
[Site] User is able to use 'Заполните анкету' function with empty fields in the form

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#14]
**Steps to reproduce:**
1. Open browser (Microsoft Edge, Chrome);
2. Open site;
3. Scroll down till the footer;
4. Click on [Заполните анкету] button;
5. Do not populate any fields. Check 'Даю согласие на обработку персональных данных' check-box and click on [Отправить] button.

**Expected result:** Request is not submited. Validation message appears: "Пожалуйста укажите Ваши данные"
**Actual result:** Request is submited. Validation message appears: "Заявка отправленна"

**Comment by followyouhome** [comment]
Actual for both feedback and coopration forms

**Comment by ypogarsky** [comment]
Passed.
