### ISSUE TITLE
[Site] [Зарегистрироваться] button is enabled without captcha check-box is checked

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#17]
**Steps to reproduce:**
1. Open site (any device / browser);
2. Navigate to 'Для клиентов' -> 'Зарегистрироваться' page;
3. Check 'Согласие с пользовательским соглашением' check-box.

**Expected result:** [Зарегистрироваться] button is disabled;
**Actual result:** [Зарегистрироваться] button is enabled.
![viber image 2019-05-22 , 23 09 31](https://user-images.githubusercontent.com/37796643/58205594-8dcfb480-7ce7-11e9-95eb-5420de71fbcc.jpg)

**Comment by followyouhome** [comment]
Added required fields + fixed this checkbox together with recaptcha

**Comment by ypogarsky** [comment]
Passed.
