### ISSUE TITLE
[Site] [ie11]Landing page promo-coupon pop-up is broken

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#18]
**Steps to reproduce:**
1. Open site first time after clearing cache and cookies.

**Expected result:** Landing page promo-coupon pop-up is displaying image. The text is aligned;
**Actual result:** Landing page promo-coupon pop-up is not displaying anything. The text is not aligned;
![Screenshot_6](https://user-images.githubusercontent.com/37796643/58439444-c226e480-80dc-11e9-94d1-f31835975dd0.jpg)

**Comment by followyouhome** [comment]
Another issue with IE 11 and flexbox, please verify

**Comment by ypogarsky** [comment]
Passed.
