### ISSUE TITLE
[Site] [ie11] Console error while navigating to the main page

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#19]
**Steps to reproduce:**
1. Open site;
2. Close promo-coupon pop-up.

**Expected result:** Site is opened. No error messages in the console;
**Actual result:** Site is opened. Error messages in the console: "SCRIPT445: Команда не поддерживается объектом".
![Screenshot_7](https://user-images.githubusercontent.com/37796643/58439648-c8699080-80dd-11e9-81c5-fd5931a0e803.jpg)

**Comment by followyouhome** [comment]
I think this one is fixed too, but please check again

**Comment by ypogarsky** [comment]
Passed.
