### ISSUE TITLE
[Site] [ie11] [Подписаться] button color is not acceptable  

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#22]
**Steps to reproduce:**
1. Open site;
2. Scroll down till the footer of the site.

**Expected result:** [Подписаться] button is orange color;
**Actual result:** [Подписаться] button is grey color.
![Screenshot_10](https://user-images.githubusercontent.com/37796643/58440340-0ec0ee80-80e2-11e9-8c16-4fddb8847e89.jpg)

**Comment by followyouhome** [comment]
Fixed, looks like CSS color inheritance doesn't work in IE 11

**Comment by ypogarsky** [comment]
Passed.
