### ISSUE TITLE
[Site] [Chrome on Samsung EDGE S7] [Зарегестрироваться] button becames availible after check-box of 'Согласие с пользовательским соглашением' only

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#26]
**Steps to reproduce:**
1. Open site;
2. Navigate to 'Регистрация' page;
3. Check 'Согласие с пользовательским соглашением'  check-box.

**Expected result:** Button [Зарегестрироваться] is not enabled until User fill the whole form;
**Actual result:** Button [Зарегестрироваться] is enabled.
![Screenshot_20190528-092656_Chrome](https://user-images.githubusercontent.com/37796643/58455972-a5fe6400-812b-11e9-9491-181b7dc6ac5a.jpg)

**Comment by followyouhome** [comment]
Added required fields for registration form

**Comment by ypogarsky** [comment]
Passed.
