### ISSUE TITLE
[Site] User is not able to navigate to the landing page. There is no button for that.

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#27]
**Steps to reproduce:**
1. Open site;
2. Navigate to any page.

**Expected result:** There is [Home] button in the main menu. Clicking on it leads User to the landing page;
**Actual result:** There is no button for that.

**Comment by followyouhome** [comment]
Added links to homepage in footer and navigation

**Comment by ypogarsky** [comment]
Passed.
