### ISSUE TITLE
[Site] [Chrome on Samsung EDGE S7] Page is opened not from the top of the page

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#28]
**Steps to reproduce:**
1. Open site;
2. Navigate to any page (e.g. 'Вечерния платья'->'Vessna 2019');
3. Scroll down the page;
4. Click on 'Условия сотрудничества' link.

**Expected result:** User is navigated to the relevant page. The page is opened from the top;
**Actual result:** User is navigated to the relevant page. The page is opened from the bottom.
![Screenshot_20190528-094921_Chrome](https://user-images.githubusercontent.com/37796643/58456875-ff679280-812d-11e9-86b9-924c559d65c5.jpg)

**Comment by followyouhome** [comment]
I think this one should be fixed with desktop fix, I checked it and for me it works. But please verify anyway.

**Comment by ypogarsky** [comment]
Passed.
