### ISSUE TITLE
[Site] [Chrome on Samsung EDGE S7] 'Форма обратной связи' and 'Заявка на сотрудничество' pop-up's fields are too short 

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#29]
**Steps to reproduce:**
1. Open site;
2. Navigate to 'Контакты' page;
3. Click on [Напишите нам] or [Заполните анкету] button. 

**Expected result:** All the fields in the form are placed as on registration form;
**Actual result:** All the fields are placed one next to an another. 'Даю согласие на обработку персональных данных' text goes beyond the screen.
![Screenshot_20190528-100343_Chrome](https://user-images.githubusercontent.com/37796643/58457706-02638280-8130-11e9-81a3-20d6c101059c.jpg)
![Screenshot_20190528-095755_Chrome](https://user-images.githubusercontent.com/37796643/58457711-05f70980-8130-11e9-8276-11d3adce0a34.jpg)

![Screenshot_20190528-100646_Chrome](https://user-images.githubusercontent.com/37796643/58458015-b9f89480-8130-11e9-8459-a60a902e75f7.jpg)
![Screenshot_20190528-100714_Chrome](https://user-images.githubusercontent.com/37796643/58458026-c0870c00-8130-11e9-981a-09b513517b62.jpg)

**Comment by followyouhome** [comment]
Good catch, also updated subsribe form and other modules on contact page

**Comment by ypogarsky** [comment]
Passed.
