### ISSUE TITLE
[Admin Panel] [IE11] User is not able to navigate through menues

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#30]
**Steps to reproduce:**
1. Open site;
2. Navigate to login page;
3. Login with Admin User role;
4. Navigate to 'Пользователи' menu.

**Expected result:** User is navigated to 'Пользователи' page;
**Actual result:** User is not navigated to 'Пользователи' page. There are errors in Console.
![image](https://user-images.githubusercontent.com/37796643/58623504-cf0f2800-82d6-11e9-9a75-f8d1c66b4ebb.png)
SCRIPT5007: Не удалось получить свойство "length" ссылки, значение которой не определено или является NULL
admin.js (20824,3)
SCRIPT5007: Не удалось получить свойство "length" ссылки, значение которой не определено или является NULL
admin.js (20824,3)
SCRIPT5007: Не удалось получить свойство "length" ссылки, значение которой не определено или является NULL
admin.js (20824,3)
SCRIPT5007: Не удалось получить свойство "length" ссылки, значение которой не определено или является NULL
admin.js (20824,3)

**Comment by followyouhome** [comment]
Known issue in KeystoneJS project https://github.com/keystonejs/keystone/issues/3734
