### ISSUE TITLE
[Admin Panel] Populating 'Email' field with Cyrillic symbols lead to unexpected behavior

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#4]
**Steps to reproduce:**
1. Login into Admin panel;
2. Navigate to 'Пользователи' page;
3. Navigate into any User with email;
4. Click on the 'Email' field;
5. Populate field with any Cyrillic symbol.

**Expected result:** The Cyrillic symbols appear in the field;
**Actual result:** Cyrillic symbols do not appear in the field. The input has unexpected behavior. 
![image](https://user-images.githubusercontent.com/37796643/58098340-02b8c680-7be2-11e9-9d78-d3a7d9f4de30.png)
![image](https://user-images.githubusercontent.com/37796643/58098373-18c68700-7be2-11e9-916e-f1964c69e2f2.png)

**Comment by followyouhome** [comment]
Created issue in KeystoneJS project https://github.com/keystonejs/keystone/issues/4928
