### ISSUE TITLE
[Admin Panel] Columns setting is reset after navigating through Admin panel

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#5]
**Steps to reproduce:**
1. Login into Admin panel;
2. Navigate to 'Пользователи' page;
3. Select all the values from 'Columns' drop-down list and click on 'Apply' button;
4. Navigate into any User profile;
5. Navigate back to the Users list.

**Expected result:** The Users list is displaying all the columns set on 3rd step;
**Actual result:** The Users list is displaying "Имя", "Адрес", "Администратор", "Доступ к материалам", "Подписка на новости" columns.

**Comment by followyouhome** [comment]
Unfortunately it's expected behaviour of Keysone.js
