### ISSUE TITLE
[Site] News page loads not form the top of window

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#7]
**Steps to reproduce:**
1. Navigate to Site;
2. Navigate to 'Новости' page;
3. Scroll to the bottom of the page and click on any news from the bottom of the page.

**Expected result:** News page is opened. User is observing news from the top of the page;
**Actual result:** News page is opened. User is observing news from the bottom of the page.

**Comment by followyouhome** [comment]
Added top scroll to route guard

**Comment by ypogarsky** [comment]
Passed.
