### ISSUE TITLE
[Site] Unexpected behavior of header menu

### ISSUE THREAD

**Issue by ypogarsky** [followyouhome/Vessna-Wedding#9]
**Steps to reproduce:**
1. Open site;
2. Click on the burger menu 'Свадебные платья' on the header;
3. Click on the burger menu 'Вечерние платья' on the header.

**Expected result:** 'X' icon of the 'Свадебные платья' changed back to burger menu; 
**Actual result:** Two 'X' icons are displaying;
![Screenshot_4](https://user-images.githubusercontent.com/37796643/58130476-bf337c00-7c24-11e9-9c79-101936de97a5.jpg)

**Comment by followyouhome** [comment]
Lol

**Comment by ypogarsky** [comment]
Passed.
